#------ user  API ------#

### get a user api endpoint
GET  http://localhost:8000/api/v1/users


###register user
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name":"john ",
    "email": " jan@doegmail.com",
    "password":"123454"
}


###login user
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
     "name":"john ",
    "email": " jan@doegmail.com",
    "password":"123454"

}


#expenses api

###get expenses
GET http://localhost:8000/api/v1/expenses



###post Expenses
POST http://localhost:8000/api/v1/expenses
Content-Type: application/json

{
    "name":"food",
    "amount":"$100",
    "date":"2022-04-19"
}



###delete expenses

DELETE http://localhost:8000/api/v1/expenses

